@extends('layouts.app')
@section('content')
<div class="material-background"></div>
<div class="container">
    <div class="card wow slideInUp">
      <div class="card-block-big">
        <h1 class="color-primary">Soltész Szilárd</h1><hr>
        <p>Az elmúlt 20 év szakmai tevékenységeim során több száz üzletkötővel, vezetővel dolgoztam közvetlenül. Számos alkalommal láttam, tapasztaltam a direkt értékesítés műfajából fakadó stressz negatív hatásait. Szembesültem a munkavállalók nehézségeivel, ahogy napi szinten kell megküzdeniük a megélhetésüket biztosító „szakmai termőföldön”. </p>
        <p>A sok emberi találkozás az üzleti munkámban hatalmas tükröt fordított felém, amely elsőnek nagyon riasztó volt, de egyben éreztem a lehetőséget, hogy jobban értsem, milyen folyamatokban vagyok benne, miért ellenkezeik már a lelkem annyira a környeztem elvárásaival szemben. Megtapasztaltam, hogy milyen hiányban szenved a mentális egészség ápolása.</p>
        <img src="/img/profile1.jpg " alt=" " class="img-responsive imgborder ml-2 mb-2 pull-right ">
        <p>Számomra mindig is fontos volt, értsem, tudjam értelmezni magam. Eldöntöttem, hogy összesítem a felhalmozott információkat, eddigi tudásomat és valamilyen más szempontrendszer szerint újra definiálom. Ehhez kértem külső segítséget, és köteleződtem el, hogy coaching ülések keretén belül kezdjek el dolgozni, ami támogatja céltudatos törekvéseimet. A találkozások során a kezdeti üzleti látásmód segítése szépen átalakult egy önismereti munkává. Nagy lelki edzés volt, a kapott reflexiók segítették a tudatosságom. Öröm volt számomra a felismerés, hogy vezetőként valójában coaching módszerrel, humán szemmel dolgoztam, s ezért tiltakozott már annyira a lelkem, amikor ütközött más látásmódokkal. Megerősödött bennem az érzés, hogy ez fejlesztenem kell, még tudatosabbá kell tennem ezt a gondolkodást. Láttam magam előtt a sok vezetői dilemmát, az embereket, akik nem értik sok esetben, hogy mi történik velük. A belső hangom előhívott számos olyan kérdést, amit nincs kinek feltenniük, mert hiányzik az ehhez szükséges biztonságot adó személy és környezet. Éreztem a megkönnyebbülést jeleként adott sóhaj mögött lévő megnyugvást, a „már értem” felfedezését. </p>
        <p>A szemléletben, a megfelelő alapokban hiszek, s amennyiben emberekkel foglalkozom, mint coach, szervezetfejlesztő, számomra csak az elfogadható, ha megismerem, miként működünk mi emberi lények, felismerjük elsődleges érzéseinket, s tudjuk értelmezni az azokból kiinduló cselekedeteinket. De a legfontosabb, hogy ismerjem magam, tudjam értelmezni az eddigi utamat, legyen önismeretem, hiszen megfelelő önismeret nélkül a tanulás, fejlődés torzulhat. Közgazdász végzettséggel jelentkeztem a Károli Gáspár Református Egyetem mentálhigiénés képzésére, hogy ezen a fontos alapozáson, saját magam „érzékenyítésén” átessek. Tudtam, hogy időben a hosszabb utat választom, de ezt a hidat meg akartam építeni, amely támogatja, hogy olyanná váljak, aki képes segíteni vezetőkön vagy más munkakörben dolgozókon, akik emberekkel foglalkoznak. Ezért döntöttem, hogy a szupervizor képzés legyen a második lépcsőfok. </p>
     
        <p>Coachként és értékesítés-stratégia tanácsadóként dolgozom saját vállalkozásomban. Szervezeti munkáim során jellemzően vezetőkkel dolgozom. Tapasztalatom szerint az üzleti témák erős kötelékében is kivétel nélkül valamilyen személyes elakadás van, amit kizárólagosan gazdasági nyelvezettel, gondolkodással nem lehet gyógyítani. Fontosnak tartottam az emberi lélek folyamatait megismerni. Számos hibás módszert láttam előző munkahelyeimen, például, valamilyen üzleti cél érdekében jelöltek ki „segítő” szakembereket értékesítők, vezetők szakmai támogatására. Kétségtelen, ezek tűnhettek nagyon jópofa megoldásnak, rövidtávon még hatékony is lehet, de tartós sikert szerintem kevésbé adhat, hiszen a lényeg szinte mindig kimaradt, a szakmai górcső alá helyezett személy egyéni elakadásának valós önfeltárásának a mechanizmusa. </p>
        </div>
    </div>
</div>
@stop